# https://github.com/EmbarkStudios/cargo-deny/blob/main/deny.template.toml

[graph]
targets = []
all-features = true
no-default-features = false

[output]
feature-depth = 1

[advisories]
ignore = [
    "RUSTSEC-2024-0384", # instant
    "RUSTSEC-2023-0071", # rsa
    "RUSTSEC-2025-0012", # backoff
]

[licenses]
confidence-threshold = 0.8
exceptions = []
allow = [
    "AGPL-3.0",
    "MIT",
    "Apache-2.0",
    "Unicode-3.0",
    "ISC",
    "CDLA-Permissive-2.0",
    "BSD-3-Clause",
    "Zlib",
]

[licenses.private]
ignore = true
registries = []

[bans]
multiple-versions = "warn"
wildcards = "warn"
highlight = "all"
workspace-default-features = "allow"
external-default-features = "allow"
allow = []
deny = []
skip = []
skip-tree = []

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []

[sources.allow-org]
# github = [""]
# gitlab = [""]
# bitbucket = [""]
