# Usage notes
#
# This file is only used in local development. 
# In order to start using these services, ensure the following conditions are met:
#
#   - An `GOOGLE_APPLICATION_CREDENTIALS` environment variable pointing to a GCP service account file.
#     Note: This is only needed when running services outside of a GCP environment.
#
#     See https://firebase.google.com/docs/admin/setup#initialize_the_sdk_in_non-google_environments
# ---
services:
  fireauth2:
    build:
      context: .
      dockerfile: ./fireauth2-server/Dockerfile
    ports:
      - 8080:8080
    # Create a .env file in the root of this project or replace the variables 
    # found in the .env.example file and rename it.
    env_file: .env
    environment:
      # Helps detecting Docker runtime
      - DOCKER_RUNNING=true
      # Google environments set this variable by default.
      # When running our services locally, however, we must provide it manually,
      - GOOGLE_APPLICATION_CREDENTIALS=/run/secrets/google-application-credentials
    secrets:
      - google-application-credentials
# Secrets shared among multiple services
secrets:
  # Google Cloud Platform service account credentials
  google-application-credentials:
    file: ${GOOGLE_APPLICATION_CREDENTIALS}
