name: Update Attributions
permissions:
  contents: write
on:
  workflow_call:
    inputs:
      commit_message:
        type: string
  workflow_dispatch:
env:
  GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
  GPG_PRIVATE_KEY_PASSPHRASE: ${{ secrets.GPG_PRIVATE_KEY_PASSPHRASE }}
jobs:
  update-attributions:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v4
      - run: git pull
      - name: Install stable toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Install cargo-attribution
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-attribution
      - name: Run cargo attribution
        run: cargo attribution
      - name: "Import GPG key"
        id: import-gpg
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ env.GPG_PRIVATE_KEY }}
          passphrase: ${{ env.GPG_PRIVATE_KEY_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
      - name: "Commit and push changes"
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_author: "${{ steps.import-gpg.outputs.name }} <${{ steps.import-gpg.outputs.email }}>"
          commit_user_name: ${{ steps.import-gpg.outputs.name }}
          commit_user_email: ${{ steps.import-gpg.outputs.email }}
          commit_message: "chore: update crate attribution"
