name: Update MSRV
permissions:
  contents: write
on:
  workflow_call:
  workflow_dispatch:
env:
  GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
  GPG_PRIVATE_KEY_PASSPHRASE: ${{ secrets.GPG_PRIVATE_KEY_PASSPHRASE }}
jobs:
  update-msrv:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v4
      - run: git pull
      - name: Install stable toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: cargo-bins/cargo-binstall@main
      - name: Install cargo-msrv
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-msrv
      - name: Get msrv data
        id: data-msrv
        run: |
          current_msrv=$(cargo msrv show --output-format minimal);
          echo "current msrv: $current_msrv";
          echo "current=$current_msrv" >> "$GITHUB_OUTPUT";
          new_msrv=$(cargo msrv find --min $current_msrv --output-format minimal);
          echo "new msrv: $new_msrv";
          echo "new=$new_msrv" >> "$GITHUB_OUTPUT";
      - name: Update cargo msrv
        run: cargo msrv set ${{ steps.data-msrv.outputs.new }}
      - name: Update readme msrv
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: ${{ steps.data-msrv.outputs.current }}
          replace: ${{ steps.data-msrv.outputs.new }}
          regex: false
          include: "README.md"
      - run: git pull
      - name: "Import GPG key"
        id: import-gpg
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ env.GPG_PRIVATE_KEY }}
          passphrase: ${{ env.GPG_PRIVATE_KEY_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
      - name: Commit and Push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "build: update MSRV from [${{steps.data-msrv.outputs.current}}] to [${{steps.data-msrv.outputs.new}}]"
